"""
Django settings for report2026 project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import environ
import os
from pathlib import Path
from celery.schedules import crontab
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
# Đọc file .env
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-l&h1%%+nd)co)hne$x4+6n0j9tr$%5*ai9zz!+==^gw&uv@b@4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]
# CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

CSRF_TRUSTED_ORIGINS = [
    "https://report.haophuong.com",
    "https://api-vending.haophuong.com"
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'import_export',
    'accounting',
    'rest_framework',
    'knox',
    'corsheaders',
    'django_celery_beat',
    'django_celery_results',
]

CELERY_RESULT_BACKEND = 'django-db'
CELERY_BROKER_URL = 'redis://localhost:6379/0'

IMPORT_EXPORT_USE_TRANSACTIONS = True

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'knox.auth.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

ROOT_URLCONF = 'report2026.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'report2026.wsgi.application'


# Database

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('DB_NAME'),
        'USER': env('DB_USER'),
        'PASSWORD': env('DB_PASSWORD'),
        'HOST': env('DB_HOST'),
        'PORT': env('DB_PORT', default='5432'),
    }
}



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Ho_Chi_Minh'

USE_I18N = True

USE_TZ = True

# Cấu hình múi giờ riêng cho Celery (để Celery Beat nhận diện đúng giờ Việt Nam)
CELERY_TIMEZONE = 'Asia/Ho_Chi_Minh'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


# Cấu hình Celery Beat Schedule động từ .env (Hỗ trợ chạy theo ngày, tuần, tháng hoặc custom)
from report2026.schedule_utils import get_import_schedule

schedule_val, IMPORT_SCHEDULE_DESC = get_import_schedule(env)

CELERY_BEAT_SCHEDULE = {
    'auto_import_excel_daily': {
        'task': 'accounting.tasks.misa_pipeline_master',
        'schedule': schedule_val,
    },
}

# Đường dẫn khởi chạy Redis Server tự động
REDIS_SERVER_PATH = r"d:\downloads\redis-x64-5.0.14.1\redis-server.exe"

# Cấu hình tự động tải báo cáo từ MISA AMIS
MISA_AMIS_LOGIN_URL = env('MISA_AMIS_LOGIN_URL', default='https://act.amis.vn/')
MISA_EMAIL = env('MISA_EMAIL', default='')
MISA_PASSWORD = env('MISA_PASSWORD', default='')
MISA_HEADLESS = env.bool('MISA_HEADLESS', default=True)
MISA_BROWSER_CHANNEL = env('MISA_BROWSER_CHANNEL', default='chrome')
MISA_EXPORT_SELECTOR = env('MISA_EXPORT_SELECTOR', default="button:has-text('Xuất khẩu')")
MISA_BROWSER_STATE_PATH = os.path.join(BASE_DIR, 'media', env('MISA_BROWSER_STATE_FILENAME', default='misa_session.json'))

MISA_REPORTS = {
    'BAN_HANG': env('MISA_URL_BAN_HANG', default=''),
    'MUA_HANG': env('MISA_URL_MUA_HANG', default=''),
    'TON_KHO': env('MISA_URL_TON_KHO', default=''),
    'CONG_NO_NCC': env('MISA_URL_CONG_NO_NCC', default=''),
    'TUOI_NO_KH': env('MISA_URL_TUOI_NO_KH', default=''),
    'SO_CHI_TIET': env('MISA_URL_SO_CHI_TIET', default=''),
}


