"""
Django settings for report2026 project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import environ
import os
from pathlib import Path
from celery.schedules import crontab
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
# Đọc file .env
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-l&h1%%+nd)co)hne$x4+6n0j9tr$%5*ai9zz!+==^gw&uv@b@4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]
# CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True


CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

CSRF_TRUSTED_ORIGINS = [
    "https://report.haophuong.com",
    "https://api-vending.haophuong.com"
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'import_export',
    'accounting',
    'rest_framework',
    'knox',
    'corsheaders',
    'django_celery_beat',
    'django_celery_results',
    'django_filters',
]

CELERY_RESULT_BACKEND = 'django-db'
CELERY_BROKER_URL = 'redis://localhost:6379/0'

IMPORT_EXPORT_USE_TRANSACTIONS = True

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'knox.auth.TokenAuthentication',
        # 'rest_framework.authentication.SessionAuthentication', ## Tắt khi deploy, bật SessionAuthentication để test API trên browser
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

ROOT_URLCONF = 'report2026.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'report2026.wsgi.application'


# Database

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('DB_NAME'),
        'USER': env('DB_USER'),
        'PASSWORD': env('DB_PASSWORD'),
        'HOST': env('DB_HOST'),
        'PORT': env('DB_PORT', default='5432'),
    }
}



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Ho_Chi_Minh'

USE_I18N = True

USE_TZ = True

# Cấu hình múi giờ riêng cho Celery (để Celery Beat nhận diện đúng giờ Việt Nam)
CELERY_TIMEZONE = 'Asia/Ho_Chi_Minh'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


# Cấu hình Celery Beat Schedule động từ .env (Hỗ trợ chạy theo ngày, tuần, tháng hoặc custom)
from report2026.schedule_utils import get_import_schedule, get_debt_reminder_schedule, get_executive_dashboard_schedule

schedule_val, IMPORT_SCHEDULE_DESC = get_import_schedule(env)

CELERY_BEAT_SCHEDULE = {
    'auto_import_excel_daily': {
        'task': 'accounting.tasks.misa_pipeline_master',
        'schedule': schedule_val,
    },
}

# -----------------------------------------------------------------------------
# CẤU HÌNH TỰ ĐỘNG GỬI EMAIL NHẮC NỢ PHÂN CẤP (SALES & TRƯỞNG BU)
# -----------------------------------------------------------------------------
# 1. AUTO_SEND_DEBT_REMINDERS_ENABLED: Công tắc tổng Bật/Tắt tự động gửi mail định kỳ (Mặc định: False để an toàn)
AUTO_SEND_DEBT_REMINDERS_ENABLED = env.bool('AUTO_SEND_DEBT_REMINDERS_ENABLED', default=False)

# 2. DEBT_REMINDER_DRY_RUN: Chế độ thử nghiệm an toàn (Mặc định: True). Khi True, KHÔNG gửi mail thật ra ngoài.
DEBT_REMINDER_DRY_RUN = env.bool('DEBT_REMINDER_DRY_RUN', default=True)

# 3. DEBT_REMINDER_TEST_EMAIL: Email nhận mẫu thử nghiệm khi chạy dry_run (Tùy chọn)
DEBT_REMINDER_TEST_EMAIL = env('DEBT_REMINDER_TEST_EMAIL', default=None)

# 4. DEBT_REMINDER_RECIPIENT_TYPE: Đối tượng nhận ('ALL', 'SALES', 'MANAGERS')
DEBT_REMINDER_RECIPIENT_TYPE = env('DEBT_REMINDER_RECIPIENT_TYPE', default='MANAGERS')

# 5. DEBT_REMINDER_CC_EMAILS: Danh sách email nhận CC (ví dụ: BOD, Kế toán trưởng)
DEBT_REMINDER_CC_EMAILS = env.list('DEBT_REMINDER_CC_EMAILS', default=[])

# 6. DEBT_REMINDER_EXCLUDE_EMAILS: Danh sách email loại trừ (Blacklist không gửi)
DEBT_REMINDER_EXCLUDE_EMAILS = env.list('DEBT_REMINDER_EXCLUDE_EMAILS', default=[])

# 7. DEBT_REMINDER_EXCLUDE_BU_CODES: Danh sách mã BU loại trừ (Blacklist không gửi email)
DEBT_REMINDER_EXCLUDE_BU_CODES = env.list('DEBT_REMINDER_EXCLUDE_BU_CODES', default=['ĐTCT', 'BU_DTCT'])

# 8. DEBT_REMINDER_BU_CODE: Mã BU cụ thể nếu muốn giới hạn gửi (None = gửi toàn bộ các BU thương mại)
DEBT_REMINDER_BU_CODE = env('DEBT_REMINDER_BU_CODE', default=None)

if AUTO_SEND_DEBT_REMINDERS_ENABLED:
    debt_schedule_val, DEBT_REMINDER_SCHEDULE_DESC = get_debt_reminder_schedule(env)
    CELERY_BEAT_SCHEDULE['auto_send_debt_reminders_periodic'] = {
        'task': 'accounting.tasks.send_debt_reminders_task',
        'schedule': debt_schedule_val,
        'kwargs': {
            'period': None,  # Mặc định tự động nhận diện kỳ mới nhất
            'dry_run': DEBT_REMINDER_DRY_RUN,
            'test_email': DEBT_REMINDER_TEST_EMAIL if DEBT_REMINDER_DRY_RUN else None,
            'bu_code': DEBT_REMINDER_BU_CODE,
            'recipient_type': DEBT_REMINDER_RECIPIENT_TYPE,
        },
    }
else:
    DEBT_REMINDER_SCHEDULE_DESC = "Đã tắt (Tạm ngưng tự động gửi mail nhắc nợ)"


# -----------------------------------------------------------------------------
# CẤU HÌNH TỰ ĐỘNG GỬI EMAIL BÁO CÁO ĐIỀU HÀNH (EXECUTIVE DASHBOARD)
# -----------------------------------------------------------------------------
# 1. AUTO_SEND_EXECUTIVE_DASHBOARD_ENABLED: Công tắc tổng Bật/Tắt tự động gửi Executive Dashboard (Mặc định: False)
AUTO_SEND_EXECUTIVE_DASHBOARD_ENABLED = env.bool('AUTO_SEND_EXECUTIVE_DASHBOARD_ENABLED', default=False)

# 2. EXECUTIVE_DASHBOARD_DRY_RUN: Chế độ thử nghiệm (Mặc định: False để gửi thật khi đã bật cấu hình)
EXECUTIVE_DASHBOARD_DRY_RUN = env.bool('EXECUTIVE_DASHBOARD_DRY_RUN', default=False)

# 3. EXECUTIVE_DASHBOARD_TO_EMAIL: Email người nhận chính (BOD / Ban Lãnh Đạo)
EXECUTIVE_DASHBOARD_TO_EMAIL = env('EXECUTIVE_DASHBOARD_TO_EMAIL', default='long.nguyenthanh@haophuong.com')

# 4. EXECUTIVE_DASHBOARD_CC_EMAILS: Danh sách email nhận CC (ngăn cách bằng dấu phẩy trong .env)
EXECUTIVE_DASHBOARD_CC_EMAILS = env.list('EXECUTIVE_DASHBOARD_CC_EMAILS', default=[])

if AUTO_SEND_EXECUTIVE_DASHBOARD_ENABLED:
    exec_schedule_val, EXECUTIVE_DASHBOARD_SCHEDULE_DESC = get_executive_dashboard_schedule(env)
    CELERY_BEAT_SCHEDULE['auto_send_executive_dashboard_periodic'] = {
        'task': 'accounting.tasks.send_executive_dashboard_task',
        'schedule': exec_schedule_val,
        'kwargs': {
            'to_email': EXECUTIVE_DASHBOARD_TO_EMAIL,
            'cc_emails': EXECUTIVE_DASHBOARD_CC_EMAILS,
            'report_date': None,  # Mặc định lấy ngày hôm nay
            'period': None,       # Mặc định lấy tháng hiện tại
            'dry_run': EXECUTIVE_DASHBOARD_DRY_RUN,
        },
    }
else:
    EXECUTIVE_DASHBOARD_SCHEDULE_DESC = "Đã tắt (Tạm ngưng tự động gửi mail Executive Dashboard)"


# Đường dẫn khởi chạy Redis Server tự động
REDIS_SERVER_PATH = r"d:\downloads\redis-x64-5.0.14.1\redis-server.exe"

# Cấu hình tự động tải báo cáo từ MISA AMIS
MISA_AMIS_LOGIN_URL = env('MISA_AMIS_LOGIN_URL', default='https://act.amis.vn/')
MISA_EMAIL = env('MISA_EMAIL', default='')
MISA_PASSWORD = env('MISA_PASSWORD', default='')
MISA_HEADLESS = env.bool('MISA_HEADLESS', default=True)
MISA_BROWSER_CHANNEL = env('MISA_BROWSER_CHANNEL', default='chrome')
MISA_EXPORT_SELECTOR = env('MISA_EXPORT_SELECTOR', default="button:has-text('Xuất khẩu')")
MISA_BROWSER_STATE_PATH = os.path.join(BASE_DIR, 'media', env('MISA_BROWSER_STATE_FILENAME', default='misa_session.json'))

USE_OPTION_EXPORT_REPORT_MISA = env.int('USE_OPTION_EXPORT_REPORT_MISA', default=2)
MISA_URL_REPORT_SAVED = env('MISA_URL_REPORT_SAVED', default='https://actapp.misa.vn/app/RP/ReportSavedList')

MISA_REPORTS = {
    'BAN_HANG': env('MISA_URL_BAN_HANG', default=''),
    'MUA_HANG': env('MISA_URL_MUA_HANG', default=''),
    'TON_KHO': env('MISA_URL_TON_KHO', default=''),
    'CONG_NO_NCC': env('MISA_URL_CONG_NO_NCC', default=''),
    'TUOI_NO_KH': env('MISA_URL_TUOI_NO_KH', default=''),
    'TAI_KHOAN_CT': env('MISA_URL_TAI_KHOAN_CT', default=''),
    'SO_DU_NH': env('MISA_URL_BALISTOFBALANCE', default='https://actapp.misa.vn/app/BA/ReportAnalysis/RPDynamicViewer/BAListOfBalance'),
    'DANH_SACH_KHACH_HANG': env('MISA_URL_CUSTOMER', default='https://actapp.misa.vn/app/DI/DICustomer'),
    'DANH_SACH_NHAN_VIEN': env('MISA_URL_EMPLOYEE', default='https://actapp.misa.vn/app/DI/DIEmployee'),
    'KHACH_HANG': env('MISA_URL_CUSTOMER', default='https://actapp.misa.vn/app/DI/DICustomer'),
    'NHAN_VIEN': env('MISA_URL_EMPLOYEE', default='https://actapp.misa.vn/app/DI/DIEmployee'),
}

# Cấu hình kỳ báo cáo mặc định khi xuất từ MISA ('Tháng này' hoặc 'Năm nay')
MISA_REPORT_PERIOD_OPTION = env('MISA_REPORT_PERIOD_OPTION', default='Tháng này')
MISA_TUOI_NO_KH_ACCOUNTS = env.list('MISA_TUOI_NO_KH_ACCOUNTS', default=['131', '1311'])

# -----------------------------------------------------------------------------
# CẤU HÌNH LOẠI TRỪ VÀ BÓC TÁCH HIỆU SUẤT DOANH THU / THU TIỀN / CÔNG NỢ
# -----------------------------------------------------------------------------

# 1. EXCLUDED_BU_CODES: Danh sách mã BU bị loại trừ khi tính hiệu suất Tổng Toàn Công Ty (TOTAL_CORP).
# - Mặc định chỉ loại trừ 'ĐTCT' (Đầu tư cho thuê - Rental investment entity) vì đây là mảng tài sản cho thuê,
#   không thuộc hoạt động thương mại/vận hành cốt lõi của công ty.
# - LƯU Ý QUAN TRỌNG: TUYỆT ĐỐI KHÔNG thêm 'Oversea' vào danh sách này, vì 'Oversea' là doanh thu bán hàng 
#   hợp lệ của công ty và cần được cộng vào Tổng Doanh Thu Tổng Công Ty, sau đó bóc tách thành Doanh Thu Oversea MTD.
EXCLUDED_BU_CODES = env.list('EXCLUDED_BU_CODES', default=['ĐTCT'])

# 2. EXCLUDED_CUSTOMER_GROUP_CODES: Danh sách mã Nhóm khách hàng bị loại trừ khỏi Doanh thu/Công nợ.
# - 'Internal': Loại trừ giao dịch mua bán nội bộ giữa các đơn vị thành viên.
EXCLUDED_CUSTOMER_GROUP_CODES = env.list('EXCLUDED_CUSTOMER_GROUP_CODES', default=['Internal'])

# 3. OVERSEA_CUSTOMER_GROUP_CODES: Danh sách mã Nhóm khách hàng được định nghĩa là Oversea (Xuất khẩu / Khách nước ngoài).
# - Dùng để nhận diện và bóc tách các chỉ số: Doanh thu Oversea MTD (mtd_revenue_oversea_actual),
#   Thực thu Oversea MTD (mtd_collection_oversea_actual) và Doanh thu không gồm Oversea (mtd_revenue_exclude_oversea_actual).
OVERSEA_CUSTOMER_GROUP_CODES = env.list('OVERSEA_CUSTOMER_GROUP_CODES', default=['Oversea', 'Overseas'])

# 4. EXCLUDED_DEBT_BU_CODES: Danh sách mã BU bị loại trừ khỏi các Báo cáo / API Công Nợ Phải Thu Thương Mại (Debt Drilldown).
# - Mặc định chỉ loại trừ 'VHC_HR' (Khối Nhân sự nội bộ).
EXCLUDED_DEBT_BU_CODES = env.list('EXCLUDED_DEBT_BU_CODES', default=['VHC_HR'])

# 5. CORE_COMMERCIAL_BU_CODES: Danh sách các Khối BU Kinh Doanh Cốt Lõi (Core Commercial Business Units).
# - Dùng cho bộ lọc hiển thị Dashboard Công nợ và Hệ thống gửi Email nhắc nợ phân cấp tự động.
CORE_COMMERCIAL_BU_CODES = env.list('CORE_COMMERCIAL_BU_CODES', default=[
    'BU_ELEVATOR',       # Thang máy (Mr Tiến Dũng)
    'BU_IBIZ PREMIUM',   # Thiết bị điện cao cấp (Mr Nhật Minh)
    'BU_ECO',            # ECO Solar (Mr Duy Hiếu)
    'BU_MANUFACTURING',  # Sản xuất - Nhà máy (Mr Xuân Quang)
    'BU_AGRITECH',       # Nông nghiệp công nghệ cao (Mr Duy Hiếu)
    'BU_SAB',            # Thủy sản thông minh SAB (Mr Hồng Quân)
    'BU_IBIZ VALUE',     # Thiết bị điện phổ thông (Mr Huy Phong)
    'ĐTCT'               # Đầu tư cho thuê (Mảng cho thuê thiết bị)
])

# 6. TARGET_RECEIVABLE_ACCOUNTS: Danh sách tài khoản mục tiêu khi tính toán công nợ phải thu thương mại (Receivables Debt).
# - Mặc định chỉ lấy TK '1311' (Phải thu khách hàng thương mại). Thiết kế dạng List để dễ mở rộng (1312, 1313...).
TARGET_RECEIVABLE_ACCOUNTS = env.list('TARGET_RECEIVABLE_ACCOUNTS', default=['1311'])

# 7. ENABLE_MANUAL_ADJUSTMENTS: Cờ bật/tắt tính toán các khoản điều chỉnh thủ công Off-MISA (Hisa-FJT, 5EX, ...).
ENABLE_MANUAL_ADJUSTMENTS = env.bool('ENABLE_MANUAL_ADJUSTMENTS', default=False)

# 8. EXCLUDED_DOC_ID_PREFIXES: Danh sách tiền tố mã chứng từ bị loại trừ khi tính doanh thu (ví dụ: thanh lý tài sản, điều chuyển nội bộ).
EXCLUDED_DOC_ID_PREFIXES = ['THANHLY']

# 9. MISA_SO_CHI_TIET_ACCOUNTS: Danh sách các tài khoản xuất chi tiết từ MISA (Sổ chi tiết tài khoản TAI_KHOAN_CT).
MISA_SO_CHI_TIET_ACCOUNTS = ['111', '112', '341', '641', '642']

# 10. MISA_EXCLUDED_BANK_ACCOUNTS: Danh sách số tài khoản ngân hàng loại trừ khi tính Tiền cuối kỳ (ví dụ: TK ngoại bảng/đặc thù).
MISA_EXCLUDED_BANK_ACCOUNTS = ['113611393939']

# Cấu hình gửi mail (Email Settings)
EMAIL_BACKEND = env('EMAIL_BACKEND', default='django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = env('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = env.int('EMAIL_PORT', default=587)
EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS', default=True)
EMAIL_USE_SSL = env.bool('EMAIL_USE_SSL', default=False)
EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default=EMAIL_HOST_USER if EMAIL_HOST_USER else 'noreply@haophuong.com')
EMAIL_DISPLAY_NAME = env('EMAIL_DISPLAY_NAME', default='Hao Phuong Reporting System')

# Cấu hình Email Admin Nhận Thông Báo SSO & Hệ Thống
ADMIN_NOTIFICATION_EMAILS = env.list('ADMIN_NOTIFICATION_EMAILS', default=[])

# Cấu hình Google OAuth2 Login & App URLs
GOOGLE_CLIENT_ID = env('GOOGLE_CLIENT_ID', default='')
ALLOWED_SSO_DOMAINS = env.list('ALLOWED_SSO_DOMAINS', default=['haophuong.com', 'gmail.com'])
FRONTEND_URL = env('FRONTEND_URL', default=None)
BACKEND_URL = env('BACKEND_URL', default=None)

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[%(asctime)s: %(levelname)s/%(name)s] %(message)s'
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'accounting': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
        'accounting.misa': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}





