"""
Django settings for report2026 project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import environ
import os
from pathlib import Path
from celery.schedules import crontab
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
# Đọc file .env
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-l&h1%%+nd)co)hne$x4+6n0j9tr$%5*ai9zz!+==^gw&uv@b@4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]
# CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

CSRF_TRUSTED_ORIGINS = [
    "https://report.haophuong.com",
    "https://api-vending.haophuong.com"
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'import_export',
    'accounting',
    'rest_framework',
    'knox',
    'corsheaders',
    'django_celery_beat',
    'django_celery_results',
]

CELERY_RESULT_BACKEND = 'django-db'
CELERY_BROKER_URL = 'redis://localhost:6379/0'

IMPORT_EXPORT_USE_TRANSACTIONS = True

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'knox.auth.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

ROOT_URLCONF = 'report2026.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'report2026.wsgi.application'


# Database

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('DB_NAME'),
        'USER': env('DB_USER'),
        'PASSWORD': env('DB_PASSWORD'),
        'HOST': env('DB_HOST'),
        'PORT': env('DB_PORT', default='5432'),
    }
}



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Ho_Chi_Minh'

USE_I18N = True

USE_TZ = True

# Cấu hình múi giờ riêng cho Celery (để Celery Beat nhận diện đúng giờ Việt Nam)
CELERY_TIMEZONE = 'Asia/Ho_Chi_Minh'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


# Cấu hình Celery Beat Schedule động từ .env (Hỗ trợ chạy theo ngày, tuần, tháng hoặc custom)
from report2026.schedule_utils import parse_days_of_week_desc, parse_days_of_month_desc, parse_cron_desc

IMPORT_SCHEDULE_TYPE = env('IMPORT_SCHEDULE_TYPE', default='daily').lower()

hour_str = env('IMPORT_SCHEDULE_HOUR', default='7')
minute_str = env('IMPORT_SCHEDULE_MINUTE', default='0')

try:
    formatted_time = f"{int(hour_str):02d}:{int(minute_str):02d}"
except (ValueError, TypeError):
    formatted_time = f"{hour_str.zfill(2)}:{minute_str.zfill(2)}"

if IMPORT_SCHEDULE_TYPE == 'daily':
    schedule_val = crontab(
        hour=hour_str,
        minute=minute_str
    )
    IMPORT_SCHEDULE_DESC = f"Hàng ngày lúc {formatted_time}"
elif IMPORT_SCHEDULE_TYPE == 'weekly':
    day_of_week = env('IMPORT_SCHEDULE_DAY_OF_WEEK', default='1')
    schedule_val = crontab(
        hour=hour_str,
        minute=minute_str,
        day_of_week=day_of_week
    )
    dow_desc = parse_days_of_week_desc(day_of_week)
    IMPORT_SCHEDULE_DESC = f"Hàng tuần ({dow_desc}) lúc {formatted_time}"
elif IMPORT_SCHEDULE_TYPE == 'monthly':
    day_of_month = env('IMPORT_SCHEDULE_DAY_OF_MONTH', default='1')
    schedule_val = crontab(
        hour=hour_str,
        minute=minute_str,
        day_of_month=day_of_month
    )
    dom_desc = parse_days_of_month_desc(day_of_month)
    IMPORT_SCHEDULE_DESC = f"Hàng tháng ({dom_desc}) lúc {formatted_time}"
elif IMPORT_SCHEDULE_TYPE == 'custom':
    cron_str = env('IMPORT_SCHEDULE_CRON', default='0 7 * * *')
    parts = cron_str.split()
    if len(parts) == 5:
        schedule_val = crontab(
            minute=parts[0],
            hour=parts[1],
            day_of_month=parts[2],
            month_of_year=parts[3],
            day_of_week=parts[4]
        )
    else:
        schedule_val = crontab(hour=7, minute=0)
    IMPORT_SCHEDULE_DESC = parse_cron_desc(cron_str)
else:
    schedule_val = crontab(hour=7, minute=0)
    IMPORT_SCHEDULE_DESC = "Hàng ngày lúc 07:00 (Mặc định)"

CELERY_BEAT_SCHEDULE = {
    'auto_import_excel_daily': {
        'task': 'accounting.tasks.auto_import_excel_from_folder',
        'schedule': schedule_val,
    },
}

# Đường dẫn khởi chạy Redis Server tự động
REDIS_SERVER_PATH = r"d:\downloads\redis-x64-5.0.14.1\redis-server.exe"


