# Generated by Django 6.0.4 on 2026-04-17 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Chi nhánh')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã thống kê')),
                ('name', models.CharField(max_length=255, verbose_name='Tên thống kê')),
                ('manager', models.CharField(blank=True, max_length=255, null=True, verbose_name='Trưởng BU')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã nhóm khách hàng')),
                ('name', models.CharField(max_length=255, verbose_name='Tên nhóm khách hàng')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã nhân viên')),
                ('name', models.CharField(max_length=255, verbose_name='Tên nhân viên')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã nhóm VTHH')),
                ('name', models.CharField(max_length=255, verbose_name='Tên nhóm VTHH')),
                ('origin', models.CharField(max_length=100, verbose_name='Nguồn gốc')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã kho')),
                ('name', models.CharField(max_length=255, verbose_name='Tên kho')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã khách hàng')),
                ('name', models.CharField(max_length=255, verbose_name='Tên khách hàng')),
                ('address', models.TextField(verbose_name='Địa điểm giao hàng')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.customergroup')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Mã hàng')),
                ('name', models.CharField(max_length=255, verbose_name='Tên hàng')),
                ('unit', models.CharField(max_length=20, verbose_name='ĐVT')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Nhãn hiệu (Trường mở rộng)')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.materialgroup', verbose_name='Nhóm VTHH')),
            ],
        ),
        migrations.CreateModel(
            name='SalesTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posting_date', models.DateField(verbose_name='Ngày hạch toán')),
                ('doc_id', models.CharField(max_length=100, verbose_name='Số chứng từ')),
                ('quantity', models.FloatField(default=0, verbose_name='Tổng số lượng bán')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Đơn giá')),
                ('sales_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Doanh số bán')),
                ('tax_percent', models.FloatField(default=0, verbose_name='% Thuế')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Thuế GTGT')),
                ('debit_acc', models.CharField(max_length=20, verbose_name='TK Nợ')),
                ('credit_acc', models.CharField(max_length=20, verbose_name='TK Có')),
                ('discount_acc', models.CharField(blank=True, max_length=20, null=True, verbose_name='TK Chiết khấu')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Chiết khấu')),
                ('actual_sales', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Doanh số thực tế')),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.branch', verbose_name='Chi nhánh')),
                ('business_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.businessunit', verbose_name='BU')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.customer', verbose_name='Khách hàng')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.employee', verbose_name='Nhân viên')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.product', verbose_name='Hàng hóa')),
                ('warehouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.warehouse', verbose_name='Kho')),
            ],
        ),
    ]
