# Generated by Django 6.0.4 on 2026-04-17 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã nhà cung cấp')),
                ('name', models.CharField(max_length=255, verbose_name='Tên nhà cung cấp')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã nhóm NCC')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên nhóm NCC')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierDebt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_debit', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Đầu kỳ - Nợ')),
                ('opening_credit', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Đầu kỳ - Có')),
                ('incurred_debit', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Phát sinh - Nợ')),
                ('incurred_credit', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Phát sinh - Có')),
                ('closing_debit', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Cuối kỳ - Nợ')),
                ('closing_credit', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Cuối kỳ - Có')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.supplier', verbose_name='Nhà cung cấp')),
            ],
            options={
                'verbose_name': 'Công nợ NCC',
                'verbose_name_plural': 'Bảng công nợ nhà cung cấp',
            },
        ),
        migrations.AddField(
            model_name='supplier',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers', to='accounting.suppliergroup'),
        ),
    ]
