# Generated by Django 6.0.4 on 2026-04-17 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_supplier_suppliergroup_supplierdebt_supplier_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salestransaction',
            options={'verbose_name': 'Chi tiết bán hàng', 'verbose_name_plural': 'Bảng chi tiết bán hàng'},
        ),
        migrations.CreateModel(
            name='AccountDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posting_date', models.DateField(blank=True, null=True, verbose_name='Ngày hạch toán')),
                ('doc_id', models.CharField(max_length=50, verbose_name='Số chứng từ')),
                ('account_number', models.CharField(max_length=20, verbose_name='Tài khoản')),
                ('account_name', models.CharField(max_length=255, verbose_name='Tên tài khoản')),
                ('offset_account', models.CharField(blank=True, max_length=20, null=True, verbose_name='TK đối ứng')),
                ('debit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Phát sinh Nợ')),
                ('credit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Phát sinh Có')),
                ('balance_debit', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Dư Nợ')),
                ('balance_credit', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Dư Có')),
                ('unit_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mã đơn vị')),
                ('unit_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên đơn vị')),
                ('unreasonable_cost', models.BooleanField(default=False, verbose_name='CP không hợp lý')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.branch', verbose_name='Chi nhánh')),
                ('business_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.businessunit', verbose_name='Mã thống kê')),
            ],
            options={
                'verbose_name': 'Sổ chi tiết tài khoản 111-112',
                'verbose_name_plural': 'Sổ chi tiết các tài khoản 111-112',
            },
        ),
    ]
