# Generated by Django 6.0.4 on 2026-04-18 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_alter_salestransaction_options_accountdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivablesAgeing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_date', models.DateField(blank=True, null=True, verbose_name='Ngày chứng từ')),
                ('total_debt', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Tổng nợ')),
                ('no_due_limit', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Không có hạn nợ')),
                ('due_0_7', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Trước hạn 0-7 ngày')),
                ('due_8_14', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Trước hạn 8-14 ngày')),
                ('due_15_21', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Trước hạn 15-21 ngày')),
                ('due_22_28', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Trước hạn 22-28 ngày')),
                ('due_29_60', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Trước hạn 29-60 ngày')),
                ('due_above_60', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Trước hạn trên 60 ngày')),
                ('due_total', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Tổng nợ trước hạn')),
                ('overdue_0_14', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Quá hạn 0-14 ngày')),
                ('overdue_15_30', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Quá hạn 15-30 ngày')),
                ('overdue_31_45', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Quá hạn 31-45 ngày')),
                ('overdue_46_60', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Quá hạn 46-60 ngày')),
                ('overdue_61_90', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Quá hạn 61-90 ngày')),
                ('overdue_91_120', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Quá hạn 91-120 ngày')),
                ('overdue_above_120', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Quá hạn trên 120 ngày')),
                ('overdue_total', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Tổng nợ quá hạn')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.branch', verbose_name='Chi nhánh')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.customer', verbose_name='Khách hàng')),
            ],
            options={
                'verbose_name': 'Chi tiết tuổi nợ',
                'verbose_name_plural': 'Bảng chi tiết tuổi nợ',
            },
        ),
    ]
