# Generated by Django 6.0.4 on 2026-04-18 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_receivablesageing'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventorySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Đầu kỳ - SL')),
                ('opening_value', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Đầu kỳ - Giá trị')),
                ('in_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Nhập kho - SL')),
                ('in_value', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Nhập kho - Giá trị')),
                ('out_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Xuất kho - SL')),
                ('out_value', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Xuất kho - Giá trị')),
                ('closing_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Cuối kỳ - SL')),
                ('closing_value', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Cuối kỳ - Giá trị')),
                ('ext_field1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Trường mở rộng 1')),
                ('ext_field2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Trường mở rộng 2')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.product', verbose_name='Hàng hóa')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.warehouse', verbose_name='Kho')),
            ],
            options={
                'verbose_name': 'Tổng hợp tồn kho',
                'verbose_name_plural': 'Bảng tổng hợp tồn kho',
            },
        ),
    ]
