# Generated by Django 6.0.4 on 2026-04-18 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_inventorysummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posting_date', models.DateField(verbose_name='Ngày hạch toán')),
                ('doc_date', models.DateField(verbose_name='Ngày chứng từ')),
                ('doc_number', models.CharField(max_length=100, verbose_name='Số chứng từ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Diễn giải')),
                ('org_unit_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mã đơn vị')),
                ('org_unit_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên đơn vị')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('purchase_value', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('vat_value', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('debit_account', models.CharField(max_length=20)),
                ('credit_account', models.CharField(max_length=20)),
                ('business_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.businessunit', verbose_name='Mã thống kê (BU)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.product', verbose_name='Hàng hóa')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.supplier', verbose_name='Nhà cung cấp')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.warehouse', verbose_name='Kho')),
            ],
            options={
                'verbose_name': 'Chi tiết mua hàng',
                'verbose_name_plural': 'Sổ chi tiết mua hàng',
            },
        ),
    ]
