# Generated by Django 6.0.4 on 2026-04-18 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_purchasedetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedetail',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.warehouse', verbose_name='Kho'),
        ),
    ]
