# Generated by Django 6.0.4 on 2026-04-20 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_user_device_token_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='device_token',
        ),
    ]
