# Generated by Django 6.0.4 on 2026-04-20 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_remove_user_device_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
