# Generated by Django 6.0.4 on 2026-04-20 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='BUPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(verbose_name='Tháng')),
                ('year', models.PositiveIntegerField(verbose_name='Năm')),
                ('mtd_revenue_plan', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Doanh thu MTD (Kế hoạch)')),
                ('mtd_revenue_actual', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Doanh thu MTD (Thực tế)')),
                ('mtd_collection_plan', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Thu tiền tháng (Kế hoạch)')),
                ('mtd_collection_actual', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Thu tiền tháng (Thực tế)')),
                ('inventory_value_plan', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Giá trị tồn kho (Kế hoạch)')),
                ('inventory_value_actual', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Giá trị tồn kho (Thực tế)')),
                ('bank_debt_plan', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Nợ ngân hàng (Kế hoạch)')),
                ('bank_debt_actual', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Nợ ngân hàng (Thực tế)')),
                ('business_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.businessunit', verbose_name='Đơn vị kinh doanh (Null = Tổng)')),
            ],
            options={
                'verbose_name': 'Chỉ số hiệu suất BU',
                'verbose_name_plural': 'Bảng theo dõi hiệu suất BU',
                'unique_together': {('business_unit', 'month', 'year')},
            },
        ),
    ]
