# Generated by Django 6.0.4 on 2026-04-20 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_buperformance'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessunit',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounting.businessunit'),
        ),
    ]
