# Generated by Django 6.0.4 on 2026-04-20 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_businessunit_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessunit',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='BU chính'),
        ),
    ]
