# Generated by Django 6.0.4 on 2026-04-21 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_businessunit_is_main'),
    ]

    operations = [
        migrations.CreateModel(
            name='BUPerformanceDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Ngày')),
                ('daily_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Doanh thu trong ngày')),
                ('daily_collection', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Thực thu trong ngày')),
                ('performance_month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='accounting.buperformance')),
            ],
            options={
                'verbose_name': 'Hiệu suất BU theo ngày',
                'ordering': ['-date'],
                'unique_together': {('performance_month', 'date')},
            },
        ),
    ]
