# Generated by Django 6.0.4 on 2026-04-22 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0015_buperformancedaily'),
    ]

    operations = [
        migrations.AddField(
            model_name='buperformance',
            name='cash_balance_actual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Tiền cuối kỳ (Thực tế)'),
        ),
        migrations.AddField(
            model_name='buperformance',
            name='cash_balance_plan',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Tiền cuối kỳ (Kế hoạch)'),
        ),
        migrations.AddField(
            model_name='buperformance',
            name='opex_actual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Chi phí vận hành (Thực tế)'),
        ),
        migrations.AddField(
            model_name='buperformance',
            name='opex_plan',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Chi phí vận hành (Kế hoạch)'),
        ),
    ]
