# Generated by Django 6.0.4 on 2026-04-23 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0016_buperformance_cash_balance_actual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='has_revenue',
            field=models.BooleanField(default=True, verbose_name='Có ghi nhận doanh thu'),
        ),
    ]
