# Generated by Django 6.0.4 on 2026-04-24 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0017_customer_has_revenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountdetail',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.customer', verbose_name='Khách hàng (Đối tượng)'),
        ),
    ]
