# Generated by Django 6.0.4 on 2026-05-12 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0018_accountdetail_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='buperformance',
            name='collection_due_actual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Đã thu (đến hạn)'),
        ),
        migrations.AddField(
            model_name='buperformance',
            name='collection_in_term_cod',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Thu trong hạn + COD'),
        ),
        migrations.AddField(
            model_name='buperformance',
            name='inventory_in_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Giá trị nhập kho trong kỳ'),
        ),
        migrations.AddField(
            model_name='buperformance',
            name='inventory_opening_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Giá trị tồn kho đầu kỳ'),
        ),
        migrations.AddField(
            model_name='buperformance',
            name='inventory_out_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Giá trị xuất kho trong kỳ'),
        ),
        migrations.AddField(
            model_name='buperformance',
            name='receivable_overdue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Nợ quá hạn'),
        ),
        migrations.AddField(
            model_name='buperformance',
            name='receivable_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Dư nợ cần thu'),
        ),
        migrations.AddField(
            model_name='customer',
            name='business_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.businessunit', verbose_name='Đơn vị kinh doanh quản lý'),
        ),
        migrations.AlterField(
            model_name='buperformance',
            name='mtd_collection_actual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Tổng thu (Thực tế)'),
        ),
        migrations.AlterField(
            model_name='buperformance',
            name='mtd_collection_plan',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Thu nợ kế hoạch'),
        ),
    ]
