# Generated by Django 6.0.4 on 2026-05-12 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0019_buperformance_collection_due_actual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='business_unit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse', to='accounting.businessunit', verbose_name='Đơn vị kinh doanh sở hữu'),
        ),
    ]
