# Generated by Django 6.0.4 on 2026-05-13 01:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0020_warehouse_business_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorysummary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Ngày tạo'),
            preserve_default=False,
        ),
    ]
