# Generated by Django 6.0.4 on 2026-05-13 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0021_inventorysummary_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='business_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouses', to='accounting.businessunit', verbose_name='Đơn vị kinh doanh sở hữu'),
        ),
    ]
