# Generated by Django 6.0.4 on 2026-05-14 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0022_alter_warehouse_business_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='inventory_in_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Giá trị nhập kho trong kỳ'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='inventory_opening_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Giá trị tồn kho đầu kỳ'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='inventory_out_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Giá trị xuất kho trong kỳ'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='inventory_value_actual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Giá trị tồn kho (Thực tế)'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='inventory_value_plan',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Giá trị tồn kho (Kế hoạch)'),
        ),
        migrations.AlterField(
            model_name='buperformance',
            name='mtd_collection_actual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Thu tiền tháng (Thực tế)'),
        ),
        migrations.AlterField(
            model_name='buperformance',
            name='mtd_collection_plan',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Thu tiền tháng (Kế hoạch)'),
        ),
    ]
