# Generated by Django 6.0.6 on 2026-06-11 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0023_warehouse_inventory_in_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='age',
            field=models.CharField(default=0, verbose_name='Tuổi'),
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(default=0, verbose_name='Giới tính'),
        ),
    ]
