# Generated by Django 6.0.6 on 2026-06-15 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0023_warehouse_inventory_in_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='Tên file / Tiến trình')),
                ('status', models.CharField(choices=[('SUCCESS', 'Thành công'), ('ERROR', 'Lỗi')], max_length=20, verbose_name='Trạng thái')),
                ('message', models.TextField(verbose_name='Nội dung tóm tắt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian chạy')),
            ],
            options={
                'verbose_name': 'Lịch sử Import',
                'verbose_name_plural': 'Lịch sử Import dữ liệu',
                'ordering': ['-created_at'],
            },
        ),
    ]
