# Generated by Django 6.0.6 on 2026-06-15 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0024_importlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importlog',
            options={'ordering': ['-start_time', '-created_at'], 'verbose_name': 'Lịch sử Import', 'verbose_name_plural': 'Lịch sử Import dữ liệu'},
        ),
        migrations.AddField(
            model_name='importlog',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian hoàn thành'),
        ),
        migrations.AddField(
            model_name='importlog',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian bắt đầu'),
        ),
        migrations.AlterField(
            model_name='importlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo'),
        ),
    ]
