# Generated by Django 6.0.6 on 2026-06-16 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0025_alter_importlog_options_importlog_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importlog',
            name='message',
            field=models.TextField(verbose_name='Nội dung chi tiết'),
        ),
    ]
