# Generated by Django 6.0.6 on 2026-06-16 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0026_alter_importlog_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importlog',
            name='status',
            field=models.CharField(choices=[('SUCCESS', '✅'), ('ERROR', '❌')], max_length=20, verbose_name='Trạng thái'),
        ),
    ]
