# Generated by Django 6.0.6 on 2026-06-16 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0027_alter_importlog_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Khách hàng', 'verbose_name_plural': 'Danh mục khách hàng'},
        ),
        migrations.AlterModelOptions(
            name='customergroup',
            options={'verbose_name': 'Nhóm khách hàng', 'verbose_name_plural': 'Danh mục nhóm khách hàng'},
        ),
    ]
