# Generated by Django 6.0.6 on 2026-06-16 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0028_alter_customer_options_alter_customergroup_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.customergroup'),
        ),
    ]
