# Generated by Django 6.0.6 on 2026-06-16 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0024_employee_age_employee_gender'),
        ('accounting', '0029_alter_customer_group'),
    ]

    operations = [
    ]
