# Generated by Django 6.0.6 on 2026-06-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0030_merge_20260616_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importlog',
            name='status',
            field=models.CharField(choices=[('SUCCESS', '✅'), ('ERROR', '❌'), ('NOTFOUND', '⚠️')], max_length=20, verbose_name='Trạng thái'),
        ),
    ]
