# Generated by Django 6.0.6 on 2026-06-17 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0031_alter_importlog_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountdetail',
            options={'verbose_name': 'Sổ chi tiết các tài khoản 111, 112, 341', 'verbose_name_plural': 'Sổ chi tiết các tài khoản 111, 112, 341'},
        ),
    ]
