# Generated by Django 6.0.6 on 2026-07-06 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0032_alter_accountdetail_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorysummary',
            options={'verbose_name': 'Hàng tồn kho', 'verbose_name_plural': 'Danh mục kho (chi tiết hàng có tại kho)'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'verbose_name': 'Kho', 'verbose_name_plural': 'Danh mục kho'},
        ),
        migrations.AddField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Đơn giá bán'),
        ),
    ]
