# Generated by Django 6.0.6 on 2026-07-10 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0033_alter_inventorysummary_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buperformance',
            name='ytd_collection_actual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Thu tiền YTD (Thực tế)'),
        ),
        migrations.AddField(
            model_name='buperformance',
            name='ytd_collection_plan',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Thu tiền YTD (Kế hoạch)'),
        ),
        migrations.AddField(
            model_name='buperformance',
            name='ytd_opex_actual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Chi phí opex YTD (Thực tế)'),
        ),
        migrations.AddField(
            model_name='buperformance',
            name='ytd_opex_plan',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Chi phí opex YTD (Kế hoạch)'),
        ),
        migrations.AddField(
            model_name='buperformance',
            name='ytd_revenue_actual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Doanh thu YTD (Thực tế)'),
        ),
        migrations.AddField(
            model_name='buperformance',
            name='ytd_revenue_plan',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Doanh thu YTD (Kế hoạch)'),
        ),
        migrations.AddField(
            model_name='inventorysummary',
            name='reporting_period',
            field=models.CharField(blank=True, db_index=True, max_length=7, null=True, verbose_name='Kỳ báo cáo'),
        ),
        migrations.AddField(
            model_name='receivablesageing',
            name='reporting_period',
            field=models.CharField(blank=True, db_index=True, max_length=7, null=True, verbose_name='Kỳ báo cáo'),
        ),
        migrations.AddField(
            model_name='supplierdebt',
            name='reporting_period',
            field=models.CharField(blank=True, db_index=True, max_length=7, null=True, verbose_name='Kỳ báo cáo'),
        ),
    ]
