# Generated by Django 6.0.6 on 2026-07-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0034_buperformance_ytd_collection_actual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buperformance',
            name='mtd_revenue_exclude_oversea_actual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Doanh thu không bao gồm Oversea MTD (Thực tế)'),
        ),
        migrations.AddField(
            model_name='buperformance',
            name='mtd_revenue_oversea_actual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Doanh thu Oversea MTD (Thực tế)'),
        ),
        migrations.AddField(
            model_name='buperformance',
            name='ytd_revenue_exclude_oversea_actual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Doanh thu không bao gồm Oversea YTD (Thực tế)'),
        ),
        migrations.AddField(
            model_name='buperformance',
            name='ytd_revenue_oversea_actual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Doanh thu Oversea YTD (Thực tế)'),
        ),
    ]
