# Generated by Django 6.0.6 on 2026-07-15 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0035_buperformance_mtd_revenue_exclude_oversea_actual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buperformancedaily',
            name='daily_opex_actual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Chi phí opex ngày (Thực tế)'),
        ),
        migrations.AddField(
            model_name='buperformancedaily',
            name='daily_opex_plan',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Chi phí opex ngày (Kế hoạch)'),
        ),
    ]
