# Generated by Django 6.0.6 on 2026-07-15 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0036_buperformancedaily_daily_opex_actual_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_account_number', models.CharField(max_length=50, verbose_name='Số tài khoản ngân hàng')),
                ('bank_name', models.CharField(max_length=255, verbose_name='Tên ngân hàng')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Số dư')),
                ('reporting_month', models.CharField(db_index=True, max_length=7, verbose_name='Tháng báo cáo')),
            ],
            options={
                'verbose_name': 'Bảng kê số dư ngân hàng',
                'verbose_name_plural': 'Bảng kê số dư ngân hàng',
                'unique_together': {('bank_account_number', 'reporting_month')},
            },
        ),
    ]
