# Generated by Django 6.0.6 on 2026-07-15 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0037_bankbalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankbalance',
            name='credit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Phát sinh Có'),
        ),
        migrations.AddField(
            model_name='bankbalance',
            name='debit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Phát sinh Nợ'),
        ),
        migrations.AddField(
            model_name='bankbalance',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Số dư đầu kỳ'),
        ),
        migrations.AlterField(
            model_name='bankbalance',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Số dư cuối kỳ'),
        ),
    ]
