# Generated by Django 6.0.6 on 2026-07-16 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0038_bankbalance_credit_amount_bankbalance_debit_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buperformance',
            name='mtd_collection_exclude_oversea_actual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Thực thu không bao gồm Oversea MTD (Thực tế)'),
        ),
        migrations.AddField(
            model_name='buperformance',
            name='mtd_collection_oversea_actual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Thực thu Oversea MTD (Thực tế)'),
        ),
        migrations.AddField(
            model_name='buperformance',
            name='ytd_collection_exclude_oversea_actual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Thực thu không bao gồm Oversea YTD (Thực tế)'),
        ),
        migrations.AddField(
            model_name='buperformance',
            name='ytd_collection_oversea_actual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Thực thu Oversea YTD (Thực tế)'),
        ),
    ]
