# Generated by Django 6.0.6 on 2026-07-23 02:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0039_buperformance_mtd_collection_exclude_oversea_actual_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(verbose_name='Tháng')),
                ('year', models.PositiveIntegerField(verbose_name='Năm')),
                ('metric_type', models.CharField(choices=[('REVENUE', 'Doanh thu MTD'), ('COLLECTION', 'Thu tiền MTD'), ('RECEIVABLES_DUE', 'Phải thu trong hạn'), ('RECEIVABLES_OVERDUE', 'Phải thu quá hạn'), ('PAYABLES', 'Phải trả nhà cung cấp'), ('INVENTORY', 'Hàng tồn kho'), ('CASH', 'Tiền cuối kỳ'), ('BANK_DEBT', 'Nợ ngân hàng'), ('OPEX', 'Chi phí vận hành OPEX')], max_length=50, verbose_name='Chỉ tiêu tài chính')),
                ('adjustment_type', models.CharField(choices=[('ADDITION', 'Cộng (+)'), ('DEDUCTION', 'Trừ (-)'), ('OVERWRITE', 'Ghi đè (=)')], default='ADDITION', max_length=20, verbose_name='Loại điều chỉnh')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Số tiền điều chỉnh (VNĐ)')),
                ('reason', models.CharField(max_length=500, verbose_name='Lý do điều chỉnh (e.g. Doanh thu Elevator Hisa-FJT ngoài MISA)')),
                ('source_file', models.FileField(blank=True, null=True, upload_to='adjustments_files/', verbose_name='File đính kèm / Chứng từ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt (Bật/Tắt)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
                ('business_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.businessunit', verbose_name='Đơn vị kinh doanh (Null = Tổng)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kế toán tạo')),
            ],
            options={
                'verbose_name': 'Điều chỉnh Phát sinh Ngoại bảng',
                'verbose_name_plural': 'Bảng Điều chỉnh Phát sinh Ngoại bảng (Off-MISA)',
            },
        ),
        migrations.CreateModel(
            name='BUTargetPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(verbose_name='Tháng')),
                ('year', models.PositiveIntegerField(verbose_name='Năm')),
                ('manager', models.CharField(blank=True, max_length=255, null=True, verbose_name='Người phụ trách')),
                ('year_revenue_target', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Mục tiêu Doanh thu Năm')),
                ('month_revenue_target', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Mục tiêu Doanh thu Tháng')),
                ('year_collection_target', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Mục tiêu Thu tiền Năm')),
                ('month_collection_target', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Mục tiêu Thu tiền Tháng')),
                ('year_inventory_target', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Mục tiêu Tồn kho Năm')),
                ('month_inventory_target', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Mục tiêu Tồn kho Tháng')),
                ('year_cash_target', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Mục tiêu Tiền cuối kỳ Năm')),
                ('month_cash_target', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Mục tiêu Tiền cuối kỳ Tháng')),
                ('year_bank_debt_target', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Mục tiêu Nợ ngân hàng Năm')),
                ('month_bank_debt_target', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Mục tiêu Nợ ngân hàng Tháng')),
                ('year_opex_target', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Mục tiêu Chi phí vận hành Năm')),
                ('month_opex_target', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Mục tiêu Chi phí vận hành Tháng')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.businessunit', verbose_name='Đơn vị kinh doanh (Null = Tổng)')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kế toán cập nhật')),
            ],
            options={
                'verbose_name': 'Chỉ tiêu Kế hoạch BU',
                'verbose_name_plural': 'Bảng Quản lý Chỉ tiêu Kế hoạch (Targets)',
                'unique_together': {('business_unit', 'month', 'year')},
            },
        ),
    ]
