# Generated by Django 6.0.6 on 2026-07-27 09:25 (manually edited to fix data migration)

import django.db.models.deletion
from django.db import migrations, models


def copy_code_to_employee_code(apps, schema_editor):
    """Copy old 'code' field value → 'employee_code', 'name' → 'full_name' for all existing rows."""
    Employee = apps.get_model('accounting', 'Employee')
    for emp in Employee.objects.all():
        if not emp.employee_code:
            emp.employee_code = emp.code or str(emp.id)
        if not emp.full_name:
            emp.full_name = emp.name or ''
        emp.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0040_manualadjustment_butargetplan'),
    ]

    operations = [
        # 1. Tạo bảng mới: JobTitle
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('title_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Chức danh')),
                ('title_name', models.CharField(max_length=255, verbose_name='Tên chức danh')),
            ],
            options={
                'verbose_name': 'Danh mục chức danh',
                'verbose_name_plural': 'Danh mục chức danh',
                'db_table': 'job_titles',
            },
        ),
        # 2. Cập nhật Meta options Employee
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Danh sách nhân viên', 'verbose_name_plural': 'Danh sách nhân viên'},
        ),
        # 3. Thêm employee_code TRƯỚC (nullable, chưa unique) để có thể copy data
        migrations.AddField(
            model_name='employee',
            name='employee_code',
            field=models.CharField(default='', max_length=20, verbose_name='Mã nhân viên'),
        ),
        # 4. Thêm full_name (nullable trước)
        migrations.AddField(
            model_name='employee',
            name='full_name',
            field=models.CharField(default='', max_length=100, verbose_name='Họ và tên'),
        ),
        # 5. Copy data từ code → employee_code và name → full_name
        migrations.RunPython(copy_code_to_employee_code, migrations.RunPython.noop),
        # 6. Xóa các field cũ SAU KHI đã copy xong
        migrations.RemoveField(model_name='employee', name='age'),
        migrations.RemoveField(model_name='employee', name='code'),
        migrations.RemoveField(model_name='employee', name='name'),
        # 7. Thêm các field mới khác
        migrations.AddField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày sinh'),
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='employee',
            name='identity_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Số CMND/CCCD'),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Số điện thoại'),
        ),
        # 8. Alter gender field
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Nam'), ('FEMALE', 'Nữ')], max_length=10, null=True, verbose_name='Giới tính'),
        ),
        # 9. Giờ mới enforce unique trên employee_code (data đã clean)
        migrations.AlterField(
            model_name='employee',
            name='employee_code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Mã nhân viên'),
        ),
        # 10. Đổi tên bảng
        migrations.AlterModelTable(
            name='employee',
            table='employees',
        ),
        # 11. Tạo bảng Department
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_code', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Mã đơn vị / Phòng ban')),
                ('department_name', models.CharField(max_length=255, verbose_name='Tên đơn vị / Phòng ban')),
                ('parent_department', models.ForeignKey(blank=True, db_column='parent_department_code', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_departments', to='accounting.department', verbose_name='Đơn vị cấp trên')),
            ],
            options={
                'verbose_name': 'Danh mục đơn vị',
                'verbose_name_plural': 'Danh mục đơn vị',
                'db_table': 'departments',
            },
        ),
        # 12. Tạo bảng EmployeeAssignment
        migrations.CreateModel(
            name='EmployeeAssignment',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Quá trình công tác')),
                ('start_date', models.DateField(verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Ngày kết thúc')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_assignments', to='accounting.department', verbose_name='Đơn vị / Phòng ban')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='accounting.employee', verbose_name='Nhân viên')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_assignments', to='accounting.jobtitle', verbose_name='Chức danh')),
            ],
            options={
                'verbose_name': 'Quá trình công tác',
                'verbose_name_plural': 'Lịch sử quá trình công tác',
                'db_table': 'employee_assignments',
            },
        ),
    ]

