# Generated by Django 5.0 on 2026-07-29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0041_jobtitle_alter_employee_options_remove_employee_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeassignment',
            name='manager',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='managed_assignments',
                to='accounting.employee',
                verbose_name='Người quản lý trực tiếp',
            ),
        ),
        migrations.AddField(
            model_name='customer',
            name='assigned_employee',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='assigned_customers',
                to='accounting.employee',
                verbose_name='Nhân viên Sales phụ trách',
            ),
        ),
    ]
