# Generated by Django 6.0.6 on 2026-07-29 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0042_employeeassignment_manager_customer_assigned_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_code',
            field=models.CharField(default='', max_length=20, unique=True, verbose_name='Mã nhân viên'),
        ),
    ]
