# Generated by Django 6.0.6 on 2026-07-29 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0043_alter_employee_employee_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeReceivableSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporting_period', models.CharField(db_index=True, max_length=7, verbose_name='Kỳ báo cáo')),
                ('is_manager', models.BooleanField(default=False, verbose_name='Là Quản lý nhóm/Trưởng phòng')),
                ('own_total_debt', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Tổng nợ cá nhân')),
                ('own_due_total', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Nợ trong hạn cá nhân')),
                ('own_overdue_total', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Nợ quá hạn cá nhân')),
                ('own_overdue_above_60', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Nợ quá hạn >60 ngày (cá nhân)')),
                ('own_overdue_above_120', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Nợ xấu >120 ngày (cá nhân)')),
                ('team_total_debt', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Tổng nợ cả nhóm')),
                ('team_due_total', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Nợ trong hạn cả nhóm')),
                ('team_overdue_total', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Nợ quá hạn cả nhóm')),
                ('team_overdue_above_120', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Nợ xấu cả nhóm (>120 ngày)')),
                ('subordinate_count', models.IntegerField(default=0, verbose_name='Số nhân viên cấp dưới')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_receivable_summaries', to='accounting.department', verbose_name='Phòng ban')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivable_summaries', to='accounting.employee', verbose_name='Nhân viên')),
            ],
            options={
                'verbose_name': 'Công nợ Nhân viên & Quản lý',
                'verbose_name_plural': 'Bảng tổng hợp công nợ Nhân viên & Quản lý',
                'db_table': 'employee_receivable_summaries',
                'unique_together': {('employee', 'reporting_period')},
            },
        ),
    ]
