# Generated by Django 6.0.6 on 2026-08-11 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0044_employeereceivablesummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivablesageing',
            name='account_code',
            field=models.CharField(blank=True, db_index=True, default='131', max_length=20, null=True, verbose_name='Tài khoản'),
        ),
    ]
