# Generated by Django 6.0.6 on 2026-08-17 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0045_receivablesageing_account_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_code',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='Mã nhân viên'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='full_name',
            field=models.CharField(default='', max_length=255, verbose_name='Họ và tên'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='identity_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Số CMND/CCCD'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='purchasedetail',
            name='credit_account',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='purchasedetail',
            name='debit_account',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='receivablesageing',
            name='account_code',
            field=models.CharField(blank=True, db_index=True, default='131', max_length=100, null=True, verbose_name='Tài khoản'),
        ),
    ]
