# Generated by Django 6.0.6 on 2026-08-28 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0047_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='google_sso_email',
            field=models.CharField(blank=True, help_text='Email Google cá nhân (Gmail) dùng để đăng nhập SSO (có thể nhập nhiều email cách nhau bởi dấu phẩy)', max_length=255, null=True, verbose_name='Email Google cá nhân liên kết'),
        ),
    ]
