# Generated by Django 6.0.6 on 2026-09-07 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0048_employee_google_sso_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100, verbose_name='Miền / Khối (e.g. Miền Bắc, Miền Nam, BU ECO...)')),
                ('sales_group', models.CharField(max_length=100, verbose_name='Nhóm hàng (e.g. Miền Bắc_Elevator, Miền Nam_Premium...)')),
                ('period', models.CharField(db_index=True, max_length=7, verbose_name='Kỳ báo cáo (YYYY-MM)')),
                ('month_target', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Kế hoạch Tháng')),
                ('year_target', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Kế hoạch Năm')),
                ('prev_target', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Kế hoạch Lũy kế các tháng trước (T1..T-1)')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang áp dụng')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_targets', to='accounting.businessunit', verbose_name='Đơn vị kinh doanh (BU)')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_targets', to='accounting.employee', verbose_name='Nhân viên Sales')),
            ],
            options={
                'verbose_name': 'Chỉ tiêu Sales',
                'verbose_name_plural': 'Bảng Quản lý Chỉ tiêu Sales (Sales Targets)',
                'db_table': 'sales_targets',
                'ordering': ['business_unit', 'display_order', 'id'],
                'unique_together': {('employee', 'business_unit', 'period')},
            },
        ),
    ]
