# Generated by Django 6.0.6 on 2026-09-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0049_salestarget'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeereceivablesummary',
            name='bad_debt_historical',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Nợ cũ khó đòi 2022-2024 (cá nhân)'),
        ),
        migrations.AddField(
            model_name='employeereceivablesummary',
            name='current_year_debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Công nợ năm 2026 (cá nhân)'),
        ),
        migrations.AddField(
            model_name='employeereceivablesummary',
            name='debt_2025',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Nợ cũ năm 2025 (cá nhân)'),
        ),
        migrations.AddField(
            model_name='employeereceivablesummary',
            name='team_bad_debt_historical',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Nợ cũ khó đòi 2022-2024 (cả nhóm)'),
        ),
        migrations.AddField(
            model_name='employeereceivablesummary',
            name='team_current_year_debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Công nợ năm 2026 (cả nhóm)'),
        ),
        migrations.AddField(
            model_name='employeereceivablesummary',
            name='team_debt_2025',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Nợ cũ năm 2025 (cả nhóm)'),
        ),
        migrations.AlterField(
            model_name='employeereceivablesummary',
            name='own_due_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Nợ trong hạn 2026 (cá nhân)'),
        ),
        migrations.AlterField(
            model_name='employeereceivablesummary',
            name='own_overdue_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Nợ quá hạn 2026 (cá nhân)'),
        ),
        migrations.AlterField(
            model_name='employeereceivablesummary',
            name='own_total_debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Tổng nợ cá nhân (toàn bộ)'),
        ),
        migrations.AlterField(
            model_name='employeereceivablesummary',
            name='team_due_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Nợ trong hạn 2026 cả nhóm'),
        ),
        migrations.AlterField(
            model_name='employeereceivablesummary',
            name='team_overdue_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Nợ quá hạn 2026 cả nhóm'),
        ),
        migrations.AlterField(
            model_name='employeereceivablesummary',
            name='team_total_debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Tổng nợ cả nhóm (toàn bộ)'),
        ),
    ]
